import {
  Student,
  StudentProgress,
  AcademicOverview,
  GpaByGrade,
  Course,
  SatScore,
  ActScore,
  ApScore,
  Extracurricular,
  Award,
  CollegeListEntry,
  PersonalStatement,
  SupplementalEssay,
  HistoricalAdmission,
  TaskItem,
  Counselor,
  ConsultationNote,
} from "./types";

export const mockCounselors: Counselor[] = [
  { id: "c1", name: "Jacob Chung", email: "bluekeyprep@gmail.com", auth_user_id: null, is_admin: true },
  { id: "c2", name: "Grace Lim", email: "grace@bluekeyprep.com", auth_user_id: null, is_admin: false },
  { id: "c3", name: "David Park", email: "david@bluekeyprep.com", auth_user_id: null, is_admin: false },
];

export const mockStudents: Student[] = [
  {
    id: "s1",
    student_name: "정서연",
    english_name: "Sarah Jung",
    current_grade: 12,
    graduation_year: 2027,
    high_school: "Seoul International School",
    school_country: "South Korea",
    school_type: "International",
    curriculum: "AP",
    citizenship: "South Korea",
    us_permanent_resident: false,
    intended_major: "Computer Science",
    secondary_major_interest: "Economics",
    career_interest: "Product Management",
    counselor_id: "c1",
    counselor_name: "Jacob Chung",
    status: "active",
    photo_url: null,
  },
  {
    id: "s2",
    student_name: "김민준",
    english_name: "Ethan Kim",
    current_grade: 11,
    graduation_year: 2028,
    high_school: "Korea International School",
    school_country: "South Korea",
    school_type: "International",
    curriculum: "IB",
    citizenship: "South Korea",
    us_permanent_resident: true,
    intended_major: "Biology",
    secondary_major_interest: "Public Health",
    career_interest: "Medicine",
    counselor_id: "c2",
    counselor_name: "Grace Lim",
    status: "active",
    photo_url: null,
  },
  {
    id: "s3",
    student_name: "이하은",
    english_name: "Hannah Lee",
    current_grade: 12,
    graduation_year: 2027,
    high_school: "Daewon Foreign Language High School",
    school_country: "South Korea",
    school_type: "Public — Foreign Language",
    curriculum: "AP",
    citizenship: "South Korea",
    us_permanent_resident: false,
    intended_major: "International Relations",
    secondary_major_interest: "Political Science",
    career_interest: "Diplomacy / Law",
    counselor_id: "c1",
    counselor_name: "Jacob Chung",
    status: "active",
    photo_url: null,
  },
  {
    id: "s4",
    student_name: "박지훈",
    english_name: "Jason Park",
    current_grade: 10,
    graduation_year: 2029,
    high_school: "Chadwick International",
    school_country: "South Korea",
    school_type: "International",
    curriculum: "IB",
    citizenship: "United States",
    us_permanent_resident: true,
    intended_major: "Mechanical Engineering",
    secondary_major_interest: "Physics",
    career_interest: "Robotics",
    counselor_id: "c3",
    counselor_name: "David Park",
    status: "active",
    photo_url: null,
  },
  {
    id: "s5",
    student_name: "최유나",
    english_name: "Yuna Choi",
    current_grade: 9,
    graduation_year: 2030,
    high_school: "Bundang International School",
    school_country: "South Korea",
    school_type: "International",
    curriculum: "AP",
    citizenship: "South Korea",
    us_permanent_resident: false,
    intended_major: "Undecided",
    secondary_major_interest: null,
    career_interest: null,
    counselor_id: "c2",
    counselor_name: "Grace Lim",
    status: "active",
    photo_url: null,
  },
];

export const mockProgress: Record<string, StudentProgress> = {
  s1: {
    student_id: "s1",
    academic_profile: 95,
    testing: 90,
    extracurricular_activities: 80,
    awards: 70,
    college_list: 85,
    common_application: 60,
    personal_statement: 55,
    supplemental_essays: 30,
    recommendation_letters: 50,
    school_documents: 40,
    financial_aid: 20,
  },
  s2: {
    student_id: "s2",
    academic_profile: 85,
    testing: 60,
    extracurricular_activities: 70,
    awards: 40,
    college_list: 30,
    common_application: 10,
    personal_statement: 5,
    supplemental_essays: 0,
    recommendation_letters: 20,
    school_documents: 10,
    financial_aid: 0,
  },
  s3: {
    student_id: "s3",
    academic_profile: 90,
    testing: 85,
    extracurricular_activities: 90,
    awards: 85,
    college_list: 95,
    common_application: 90,
    personal_statement: 100,
    supplemental_essays: 75,
    recommendation_letters: 80,
    school_documents: 70,
    financial_aid: 50,
  },
  s4: {
    student_id: "s4",
    academic_profile: 65,
    testing: 30,
    extracurricular_activities: 55,
    awards: 20,
    college_list: 10,
    common_application: 0,
    personal_statement: 0,
    supplemental_essays: 0,
    recommendation_letters: 0,
    school_documents: 10,
    financial_aid: 0,
  },
  s5: {
    student_id: "s5",
    academic_profile: 40,
    testing: 0,
    extracurricular_activities: 25,
    awards: 0,
    college_list: 0,
    common_application: 0,
    personal_statement: 0,
    supplemental_essays: 0,
    recommendation_letters: 0,
    school_documents: 0,
    financial_aid: 0,
  },
};

export const mockAcademicOverview: Record<string, AcademicOverview> = {
  s1: { student_id: "s1", unweighted_gpa: 3.92, weighted_gpa: 4.45, gpa_scale: 4.0, class_rank: 4, class_size: 210, percentile: 98.1, school_does_not_rank: false },
  s2: { student_id: "s2", unweighted_gpa: 3.78, weighted_gpa: 4.1, gpa_scale: 4.0, class_rank: null, class_size: null, percentile: null, school_does_not_rank: true },
  s3: { student_id: "s3", unweighted_gpa: 3.97, weighted_gpa: 4.52, gpa_scale: 4.0, class_rank: 1, class_size: 320, percentile: 99.7, school_does_not_rank: false },
  s4: { student_id: "s4", unweighted_gpa: 3.55, weighted_gpa: 3.9, gpa_scale: 4.0, class_rank: null, class_size: null, percentile: null, school_does_not_rank: true },
  s5: { student_id: "s5", unweighted_gpa: 3.85, weighted_gpa: 3.85, gpa_scale: 4.0, class_rank: null, class_size: null, percentile: null, school_does_not_rank: true },
};

export const mockGpaByGrade: GpaByGrade[] = [
  { id: "g1", student_id: "s1", grade_level: 9, subject: "overall", gpa: 3.8, notes: null },
  { id: "g2", student_id: "s1", grade_level: 10, subject: "overall", gpa: 3.9, notes: null },
  { id: "g3", student_id: "s1", grade_level: 11, subject: "overall", gpa: 3.97, notes: null },
  { id: "g4", student_id: "s1", grade_level: 12, subject: "overall", gpa: 4.0, notes: "First semester" },
];

export const mockCourses: Course[] = [
  { id: "co1", student_id: "s1", course_name: "AP Calculus BC", grade_level: 11, academic_year: "2025-2026", course_level: "AP", subject_area: "STEM" },
  { id: "co2", student_id: "s1", course_name: "AP Computer Science A", grade_level: 11, academic_year: "2025-2026", course_level: "AP", subject_area: "STEM" },
  { id: "co3", student_id: "s1", course_name: "AP English Literature", grade_level: 12, academic_year: "2026-2027", course_level: "AP", subject_area: "Humanities" },
];

export const mockSat: SatScore[] = [
  { id: "sat1", student_id: "s1", test_date: "2025-11-01", total_score: 1540, reading_writing: 760, math: 780 },
  { id: "sat2", student_id: "s1", test_date: "2025-08-01", total_score: 1490, reading_writing: 720, math: 770 },
];

export const mockAct: ActScore[] = [];

export const mockAp: ApScore[] = [
  { id: "ap1", student_id: "s1", subject: "Calculus BC", score: 5, test_date: "2026-05-01" },
  { id: "ap2", student_id: "s1", subject: "Computer Science A", score: 5, test_date: "2026-05-01" },
];

export const mockExtracurriculars: Extracurricular[] = [
  {
    id: "ec1",
    student_id: "s1",
    activity_name: "Robotics Club",
    category: "STEM / Technology",
    organization: "Seoul International School",
    position_role: "Team Captain",
    grades_participated: "10, 11, 12",
    start_date: null,
    end_date: null,
    hours_per_week: 8,
    weeks_per_year: 30,
    description: "Led a 12-person FRC robotics team; designed the autonomous navigation module.",
    achievements: "Regional finalist, 2026 FRC Korea Regional",
    quantifiable_impact: "Grew club membership from 8 to 24 students over two years",
    leadership: "Team Captain, recruited and trained underclassmen",
    major_relevance: "Directly relevant to Computer Science",
    common_app_activity: true,
    status: "Impact Created",
    rating_strength: 5,
    rating_leadership: 5,
    rating_impact: 4,
    rating_uniqueness: 3,
    rating_major_relevance: 5,
  },
  {
    id: "ec2",
    student_id: "s1",
    activity_name: "Model United Nations",
    category: "Leadership / Debate",
    organization: "Seoul International School",
    position_role: "Delegate, then Secretary-General",
    grades_participated: "9, 10, 11",
    start_date: null,
    end_date: null,
    hours_per_week: 4,
    weeks_per_year: 25,
    description: "Represented four countries across three years of conferences.",
    achievements: "Best Delegate, SEOMUN 2025",
    quantifiable_impact: null,
    leadership: "Secretary-General of school MUN chapter",
    major_relevance: "Supports Economics interest",
    common_app_activity: true,
    status: "Common App Ready",
    rating_strength: 4,
    rating_leadership: 4,
    rating_impact: 3,
    rating_uniqueness: 3,
    rating_major_relevance: 3,
  },
];

export const mockAwards: Award[] = [
  {
    id: "aw1",
    student_id: "s1",
    award_name: "USA Computing Olympiad — Gold Division",
    organization: "USACO",
    grade_level: 11,
    award_level: "International",
    placement: "Top 5%",
    num_participants: 8000,
    selectivity: "Highly selective",
    description: null,
    academic_area: "Computer Science",
    major_relevance: "Directly relevant",
  },
];

export const mockPersonalStatements: Record<string, PersonalStatement> = {
  s1: {
    student_id: "s1",
    status: "Revision 1",
    topic: "Growing up between two languages and what it taught me about translation as a form of empathy.",
    draft_link: "https://docs.google.com/document/d/example-s1-ps",
    last_updated: "2026-09-02T00:00:00Z",
  },
  s3: {
    student_id: "s3",
    status: "First Draft",
    topic: "How founding the school's coding club shaped my view of teaching as a form of leadership.",
    draft_link: null,
    last_updated: "2026-08-20T00:00:00Z",
  },
};

export const mockSupplementalEssays: SupplementalEssay[] = [
  {
    id: "se1",
    student_id: "s1",
    college_list_id: "cl1",
    university_name: "Cornell University",
    prompt: "Why are you drawn to studying the major you have selected?",
    word_limit: 650,
    status: "Revision 1",
    draft_link: "https://docs.google.com/document/d/example-se1",
    counselor: "Jacob Chung",
    editor: null,
    counselor_comments: "Strong opening — tighten the middle paragraph before next pass.",
    last_updated: "2026-09-10T00:00:00Z",
  },
];

export const mockCollegeList: CollegeListEntry[] = [
  {
    id: "cl1",
    student_id: "s1",
    category: "Reach",
    university_name: "Cornell University",
    intended_major: "Computer Science",
    application_round: "ED",
    application_deadline: "2026-11-01",
    student_preference_level: 5,
    parent_preference_level: 5,
    counselor_recommendation: "Strong reach — apply ED for admissions boost",
    application_status: "In Progress",
    notes: "Engineering supplement needs another revision pass.",
    checklist: {
      college_list_id: "cl1",
      college_added: true,
      major_selected: true,
      common_app_profile: true,
      activities: true,
      honors: true,
      personal_statement: true,
      supplemental_essays: false,
      counselor_recommendation: true,
      teacher_recommendation_1: true,
      teacher_recommendation_2: false,
      transcript: true,
      test_scores_submission: true,
      financial_aid: false,
      application_submitted: false,
    },
  },
  {
    id: "cl2",
    student_id: "s1",
    category: "High Target",
    university_name: "University of Michigan",
    intended_major: "Computer Science",
    application_round: "EA",
    application_deadline: "2026-11-01",
    student_preference_level: 4,
    parent_preference_level: 4,
    counselor_recommendation: "Strong EA option",
    application_status: "Not Started",
    notes: null,
  },
  {
    id: "cl3",
    student_id: "s1",
    category: "Target",
    university_name: "University of Wisconsin—Madison",
    intended_major: "Computer Science",
    application_round: "RD",
    application_deadline: "2027-01-15",
    student_preference_level: 3,
    parent_preference_level: 3,
    counselor_recommendation: null,
    application_status: "Not Started",
    notes: null,
  },
  {
    id: "cl4",
    student_id: "s1",
    category: "Safety",
    university_name: "Purdue University",
    intended_major: "Computer Science",
    application_round: "RD",
    application_deadline: "2027-01-15",
    student_preference_level: 3,
    parent_preference_level: 4,
    counselor_recommendation: "Solid safety with strong CS program",
    application_status: "Not Started",
    notes: null,
  },
];

export const mockTasks: TaskItem[] = [
  { id: "t1", student_id: "s1", task: "Finalize Cornell engineering supplement", assigned_to: "Sarah", deadline: "2026-10-10", priority: "High", status: "In Progress", notes: null },
  { id: "t2", student_id: "s1", task: "Request teacher recommendation #2", assigned_to: "Jacob Chung", deadline: "2026-10-05", priority: "High", status: "Not Started", notes: "Ask AP CS teacher" },
  { id: "t3", student_id: "s2", task: "Book SAT retake", assigned_to: "Ethan", deadline: "2026-12-01", priority: "Medium", status: "Not Started", notes: null },
  { id: "t4", student_id: "s4", task: "Draft initial college list", assigned_to: "David Park", deadline: "2026-10-20", priority: "Medium", status: "Waiting", notes: null },
];

export const mockHistoricalAdmissions: HistoricalAdmission[] = [
  { id: "ha1", graduation_year: 2025, high_school: "Seoul International School", gpa: 3.95, sat_score: 1540, act_score: null, curriculum: "AP", intended_major: "Computer Science", ec_strength: 5, awards_strength: 4, application_round: "ED", university_name: "Cornell University", admission_result: "Accepted" },
  { id: "ha2", graduation_year: 2025, high_school: "Korea International School", gpa: 3.8, sat_score: 1490, act_score: null, curriculum: "IB", intended_major: "Computer Science", ec_strength: 4, awards_strength: 3, application_round: "RD", university_name: "Cornell University", admission_result: "Waitlisted" },
  { id: "ha3", graduation_year: 2024, high_school: "Seoul International School", gpa: 3.7, sat_score: 1450, act_score: null, curriculum: "AP", intended_major: "Economics", ec_strength: 3, awards_strength: 3, application_round: "RD", university_name: "Cornell University", admission_result: "Rejected" },
  { id: "ha4", graduation_year: 2025, high_school: "Chadwick International", gpa: 3.9, sat_score: 1520, act_score: null, curriculum: "AP", intended_major: "Business", ec_strength: 5, awards_strength: 5, application_round: "ED", university_name: "University of Pennsylvania", admission_result: "Accepted" },
  { id: "ha5", graduation_year: 2024, high_school: "Seoul International School", gpa: 3.75, sat_score: 1470, act_score: null, curriculum: "AP", intended_major: "Business", ec_strength: 3, awards_strength: 3, application_round: "RD", university_name: "University of Pennsylvania", admission_result: "Rejected" },
  { id: "ha6", graduation_year: 2025, high_school: "Korea International School", gpa: 3.6, sat_score: 1380, act_score: null, curriculum: "IB", intended_major: "Psychology", ec_strength: 4, awards_strength: 2, application_round: "RD", university_name: "University of Michigan", admission_result: "Accepted" },
  { id: "ha7", graduation_year: 2024, high_school: "Seoul International School", gpa: 3.5, sat_score: 1340, act_score: null, curriculum: "AP", intended_major: "Psychology", ec_strength: 3, awards_strength: 2, application_round: "RD", university_name: "University of Michigan", admission_result: "Accepted" },
];

export const mockConsultationNotes: ConsultationNote[] = [
  {
    id: "cn1",
    student_id: "s1",
    counselor_id: "c1",
    counselor_name: "Jacob Chung",
    meeting_date: "2026-09-05",
    attendees: "정서연, 학부모",
    content: "코넬 ED 에세이 초안 리뷰. 학부모님께서 안전지원 학교 추가를 요청하심 — Purdue 검토 후 리스트에 추가하기로 함. 다음 미팅 전까지 추천서 요청 완료 예정.",
    created_at: "2026-09-05T10:00:00Z",
    updated_at: "2026-09-05T10:00:00Z",
  },
  {
    id: "cn2",
    student_id: "s1",
    counselor_id: "c1",
    counselor_name: "Jacob Chung",
    meeting_date: "2026-09-19",
    attendees: "정서연",
    content: "SAT 12월 재시험 일정 확정. 위스콘신-매디슨 지원 에세이 아웃라인 작성 시작. 다음 미팅은 10월 3일.",
    created_at: "2026-09-19T10:00:00Z",
    updated_at: "2026-09-19T10:00:00Z",
  },
  {
    id: "cn3",
    student_id: "s2",
    counselor_id: "c2",
    counselor_name: "Grace Lim",
    meeting_date: "2026-09-12",
    attendees: "학부모",
    content: "SAT 재시험 일정 관련 상담. 여름방학 활동 계획 논의.",
    created_at: "2026-09-12T10:00:00Z",
    updated_at: "2026-09-12T10:00:00Z",
  },
];
